text=("today is  tuesday")
string=len(text)
print(string)
object=text.upper()
print(object)
number=text.index("d")
print(number)
one=text[-3:]
print(one)
checking=text.islower()
print(checking)
book=text.count(" ")
print(book)
hi=text.isupper()
print(hi)
four=text.count("t")
print(four)
five=text.capitalize("i")
print(five)
